name: Advanced OpenWrt WR3000 Custom Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *" # Daily 03:00 UTC build

env:
  OPENWRT_REPO: https://github.com/openwrt/openwrt.git  # GitHub mirror for stability
  OPENWRT_BRANCH: openwrt-24.10
  GL_MT6000_REPO: https://github.com/Christian720420/GL-MT6000.git
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  DL_DIR: ${{ github.workspace }}/dl

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 600
    strategy:
      matrix:
        device: [cudy_wr3000-v1]
    env:
      DEVICE: ${{ matrix.device }}
      CONFIG_FILE: "wr3000.config"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Downloads
        uses: actions/cache@v4
        with:
          path: ${{ env.DL_DIR }}
          key: dl-${{ runner.os }}-${{ hashFiles(env.CONFIG_FILE) }}
          restore-keys: dl-${{ runner.os }}-

      - name: Cache CCACHE
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ matrix.device }}-${{ hashFiles(env.CONFIG_FILE) }}
          restore-keys: ccache-${{ runner.os }}-${{ matrix.device }}-

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y \
            build-essential libncurses-dev libssl-dev zlib1g-dev libtool-bin \
            autoconf automake pkg-config git curl wget ccache rsync gawk unzip time \
            python3-setuptools quilt diffstat ed gettext subversion mold

      - name: Setup ccache
        run: |
          mkdir -p "$CCACHE_DIR"
          export CCACHE_DIR="$CCACHE_DIR"
          export PATH="/usr/lib/ccache:$PATH"
          ccache -M 20G
          ccache -z
        shell: bash

      - name: Clean Old Build
        run: |
          rm -rf openwrt
          mkdir -p "$DL_DIR"

      - name: Configure Git
        run: |
          git config --global http.postBuffer 1048576000  # 1 GB buffer for large transfers
          git config --global http.version HTTP/1.1
          git config --global http.lowSpeedLimit 0
          git config --global http.lowSpeedTime 999999

      - name: Clone OpenWrt Base
        run: |
          for i in {1..5}; do
            git clone --depth 1 -b "$OPENWRT_BRANCH" "$OPENWRT_REPO" openwrt && break || {
              echo "Clone attempt $i failed, retrying in 15s..."
              sleep 15
              rm -rf openwrt  # Clean up partial clone
            }
          done

      - name: Clone GL-MT6000 Customs
        run: |
          git clone --depth 1 "$GL_MT6000_REPO" gl-mt6000

      - name: Apply Custom Files
        run: |
          cd openwrt
          if [ -d ../gl-mt6000/files ]; then
            cp -r ../gl-mt6000/files/* files/ 2>/dev/null || true
            echo "Custom files applied: SSH hardening, UCI defaults, upgrade script"
          fi
          if [ -f ../gl-mt6000/mt6000.config ]; then
            echo "GL-MT6000 config available for reference; ensure wr3000.config includes desired packages (e.g., luci-app-pbr, adblock)"
          fi

      - name: Update and Install Feeds
        run: |
          cd openwrt
          git config --global http.postBuffer 1048576000
          for i in {1..5}; do
            ./scripts/feeds update -a && break || {
              echo "Feed update attempt $i failed, retrying in 15s..."
              sleep 15
            }
          done
          ./scripts/feeds install -a

      - name: Apply Custom Config
        run: |
          cp "$CONFIG_FILE" openwrt/.config
          cd openwrt
          make defconfig

      - name: Download Sources
        run: |
          cd openwrt
          make download -j"$(nproc)" V=s || make download -j1 V=s

      - name: Build Firmware
        run: |
          cd openwrt
          export CCACHE_DIR="$CCACHE_DIR"
          export PATH="/usr/lib/ccache:$PATH"
          export LD=mold
          make -j"$(nproc)" V=s || make -j1 V=s

      - name: Optimize Binaries
        run: |
          cd openwrt/bin/targets/*/*
          find . -type f -name "*sysupgrade*.bin" -exec strip --strip-unneeded {} \; || true
          gzip -9 *sysupgrade*.bin || true

      - name: Generate Checksums
        run: |
          cd openwrt/bin/targets/*/*
          sha256sum *sysupgrade*.bin.gz > SHA256SUMS.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-${{ matrix.device }}-custom
          path: openwrt/bin/targets/*/*

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd openwrt/bin/targets/*/*
          DATE=$(date +%F)
          RELEASE_NAME="${DEVICE}-custom-${DATE}"
          gh release delete "$RELEASE_NAME" --cleanup-tag -y 2>/dev/null || true
          gh release create "$RELEASE_NAME" \
            --title "Custom OpenWrt $DEVICE Build ($DATE)" \
            --notes "Adapted from GL-MT6000 customs: SSH hardening, UCI QoL, WireGuard/PBR/AdBlock/QoS. Built with ccache and optimizations." \
            *sysupgrade*.bin.gz SHA256SUMS.txt

      - name: Build Summary
        run: |
          cd openwrt/bin/targets/*/*
          IMAGE_SIZE=$(du -h *sysupgrade*.bin.gz | cut -f1)
          echo "### Custom Build Summary for $DEVICE" >> $GITHUB_STEP_SUMMARY
          echo "- Image size: $IMAGE_SIZE" >> $GITHUB_STEP_SUMMARY
          echo "- CCACHE Stats:" >> $GITHUB_STEP_SUMMARY
          ccache -s >> $GITHUB_STEP_SUMMARY
          echo "- Base Repo: Official OpenWrt + GL-MT6000 customs" >> $GITHUB_STEP_SUMMARY
          echo "- OpenWrt Branch: $OPENWRT_BRANCH" >> $GITHUB_STEP_SUMMARY
          echo "- Config File: $CONFIG_FILE (WR3000 params + customs)" >> $GITHUB_STEP_SUMMARY
