name: Build OpenWrt WR3000 Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      CONFIG_FILE: wr3000.config
      OPENWRT_BRANCH: openwrt-24.10
      CCACHE_DIR: /home/runner/.ccache
      CCACHE_MAXSIZE: 5G

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean old build directories
        run: |
          rm -rf openwrt
          mkdir -p $CCACHE_DIR

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y build-essential ccache git python3 unzip wget rsync time libncurses-dev libssl-dev zlib1g-dev

      - name: Restore ccache cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ env.OPENWRT_BRANCH }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ env.OPENWRT_BRANCH }}-
            ccache-${{ runner.os }}-
            ccache-

      - name: Clone OpenWrt & update feeds
        run: |
          set -eux
          git clone https://github.com/openwrt/openwrt.git -b $OPENWRT_BRANCH openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
