name: Build OpenWrt WR3000 Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      CONFIG_FILE: wr3000.config
      OPENWRT_BRANCH: openwrt-24.10
      CCACHE_DIR: /home/runner/.ccache

    steps:
      - name: Build firmware (using ccache)
  run: |
    cd openwrt
    export CCACHE_DIR=$CCACHE_DIR
    export PATH="/usr/lib/ccache:$PATH"
    ccache -z
    make -j$(nproc) V=s
    ccache -s

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean old build directories
        run: |
          rm -rf openwrt
          rm -rf $CCACHE_DIR || true
          mkdir -p $CCACHE_DIR

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache git python3 unzip wget rsync time

      - name: Clone OpenWrt & update feeds
        run: |
          set -eux
          git clone https://github.com/openwrt/openwrt.git -b $OPENWRT_BRANCH openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy custom configuration
        run: |
          cp $CONFIG_FILE openwrt/.config
          cd openwrt
          make defconfig

      - name: Build firmware
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s

      - name: Show build size
        run: |
          cd openwrt
          ls -lh bin/targets/*/*/

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-wr3000-firmware
          path: openwrt/bin/targets/
