name: Advanced OpenWrt WR3000 Custom Build

on:
  workflow_dispatch:
    inputs:
      fast:
        description: 'Enable fast build mode (lighter config, tmpfs use if available)'
        required: false
        default: 'false'
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *" # Daily 03:00 UTC build

env:
  OPENWRT_REPO: https://github.com/openwrt/openwrt.git  # GitHub mirror for stability
  OPENWRT_BRANCH: openwrt-24.10

jobs:
  build:
    runs-on: self-hosted
    env:
      CCACHE_DIR: /mnt/ccache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3 python3-stdlib rsync unzip zlib1g-dev file wget curl ca-certificates \
            pigz ninja-build mold lld

      - name: Tune git for stability
        run: |
          git config --global http.postBuffer 524288000
          git config --global http.lowSpeedLimit 0
          git config --global http.lowSpeedTime 999999
          git config --global core.compression 0

      - name: Clone OpenWrt source
        run: |
          git clone --depth 1 -b ${OPENWRT_BRANCH} ${OPENWRT_REPO} openwrt

      - name: Replace feeds with GitHub mirrors
        working-directory: ./openwrt
        run: |
          cat > feeds.conf.default <<'EOF'
          src-git packages https://github.com/openwrt/packages.git;openwrt-24.10
          src-git luci https://github.com/openwrt/luci.git;openwrt-24.10
          src-git routing https://github.com/openwrt/routing.git;openwrt-24.10
          src-git telephony https://github.com/openwrt/telephony.git;openwrt-24.10
          EOF

      - name: Cache OpenWrt feeds
        uses: actions/cache@v4
        with:
          path: openwrt/feeds/
          key: feeds-${{ hashFiles('openwrt/feeds.conf.default') }}

      - name: Update & install feeds (with retry)
        working-directory: ./openwrt
        run: |
          for i in {1..5}; do
            ./scripts/feeds update -a && break || sleep 20
          done
          ./scripts/feeds install -a

      - name: Configure build
        working-directory: ./openwrt
        run: |
          cp ../.config . || echo 'No custom config provided'
          make defconfig

      - name: Build OpenWrt
        working-directory: ./openwrt
        run: |
          make -j$(nproc) V=s

      - name: Compress firmware
        if: success()
        working-directory: ./openwrt/bin/targets
        run: |
          find . -type f -name '*.bin' -exec pigz -9 {} +

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-wr3000-firmware
          path: openwrt/bin/targets/**/*.bin.gz