name: Build OpenWrt for GL-MT6000 (Self-Hosted)

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "38 1 * * *" # build daily at 01:38 UTC

env:
  OPENWRT_REPO: https://github.com/openwrt/openwrt.git
  OPENWRT_BRANCH: openwrt-24.10
  CONFIG_FILE: wr3000.config
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_COMPRESS: 1
  CCACHE_COMPILERCHECK: content
  CC: "ccache gcc"
  CXX: "ccache g++"

jobs:
  build:
    name: Build OpenWrt (GL-MT6000) on Self Runner
    runs-on: self-hosted

    steps:
      # Checkout your GL-MT6000 repo (the repo that holds .config)
      - name: Checkout GL-MT6000 repository
        uses: actions/checkout@v4
        with:
          repository: Christian720420/GL-MT6000
          path: source_repo

      # Install required dependencies (runs locally once)
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential libncurses-dev libssl-dev \
            python3-setuptools zlib1g-dev libtool \
            autoconf automake pkg-config git curl wget \
            ccache

      # Cache ccache data to speed up rebuilds
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: selfrunner-ccache-${{ hashFiles('source_repo/*.config') }}
          restore-keys: |
            selfrunner-ccache-

      # Print current ccache stats
      - name: Show ccache status
        run: |
          ccache -s || true

      # Clone OpenWrt source
      - name: Clone OpenWrt
        run: |
          git clone --depth=1 -b ${{ env.OPENWRT_BRANCH }} ${{ env.OPENWRT_REPO }} openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # Copy .config and optional files/
      - name: Prepare OpenWrt build
        run: |
          cd openwrt
          if [ -f "../source_repo/${{ env.CONFIG_FILE }}" ]; then
            cp "../source_repo/${{ env.CONFIG_FILE }}" .config
          else
            echo "❌ Config file missing!"
            exit 1
          fi

          if [ -d "../source_repo/files" ]; then
            cp -r ../source_repo/files ./
          fi

          make defconfig

      # Build firmware
      - name: Build firmware
        run: |
          cd openwrt
          make download -j1 || { sleep 10; make download -j1 V=s; }

          # Try parallel build, fallback to 1 core if error
          make -j$(nproc) V=s || { sleep 10; make -j1 V=s; }

          mkdir -p ../firmware
          find ./bin -type f \( -iname 'openwrt-*-sysupgrade.bin' -or -iname 'sha256sums' -or -iname 'config.buildinfo' \) -exec mv -v {} ../firmware/ \; ||:
          mv .config ../firmware/full.config ||:

      # Upload firmware as artifact
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gl-mt6000-firmware
          path: firmware/*

      # Create a GitHub release
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RELEASE_DATE=$(date +%F)
          set +e
          gh release delete "gl-mt6000-${RELEASE_DATE}" --cleanup-tag -y --repo "${{ github.repository }}" >/dev/null 2>&1
          set -e
