name: Build OpenWrt for Cudy WR3000

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: 'OpenWrt version'
        default: 'openwrt-24.10'
      target:
        description: 'Target'
        default: 'mediatek/filogic'
      profile:
        description: 'Device profile'
        default: 'cudy_wr3000-v1'

jobs:
  build:
    runs-on: self-hosted  # Optimized for self-hosted; add label e.g., self-hosted:openwrt-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache OpenWrt downloads, feeds, toolchain, and ccache
        uses: actions/cache@v4  # v4 for better performance
        with:
          path: |
            openwrt/dl
            openwrt/feeds
            openwrt/staging_dir
            openwrt/tmp
            ~/.ccache
          key: ${{ runner.os }}-openwrt-${{ github.event.inputs.openwrt_version }}-${{ hashFiles('.config') }}-${{ hashFiles('openwrt/feeds.conf.default') }}
          restore-keys: ${{ runner.os }}-openwrt-${{ github.event.inputs.openwrt_version }}-

      - name: Install dependencies and ccache (skip if pre-installed)
        run: |
          if ! command -v ccache &> /dev/null; then
            sudo apt update
            sudo apt install -y ccache
          fi
          sudo apt update || true  # Silent if already updated
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
          g++-multilib gettext git libncurses5-dev libssl-dev rsync unzip zlib1g-dev \
          file wget subversion python3 python3-pip python3-lib2to3 || true  # Conditional install

      - name: Clone OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git -b ${{ github.event.inputs.openwrt_version }}
          if [ -f .config ]; then
            mv .config openwrt/.config
          else
            echo "Error: .config file not found in repository root"
            exit 1
          fi
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a  # Selective via .config

      - name: Configure and build with ccache
        run: |
          cd openwrt
          make defconfig
          export CC="ccache gcc"
          export CXX="ccache g++"
          export CCACHE_DIR="$HOME/.ccache"
          export CCACHE_BASEDIR="$PWD"
          export CCACHE_LOGFILE="$PWD/ccache.log"
          make download -j$(nproc)
          make -j$(nproc) V=s CC="ccache gcc" CXX="ccache g++"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-cudy-wr3000
          path: openwrt/bin/targets/mediatek/filogic/
