name: Build OpenWrt for Cudy WR3000

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "38 1 * * *"

env:
  OPENWRT_REPO: https://github.com/openwrt/openwrt.git
  OPENWRT_BRANCH: openwrt-24.10
  CONFIG_FILE: wr3000.config
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Build OpenWrt (Cudy WR3000)
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Install dependencies
        run: |
          sudo apt remove -y '*cloud*' '*firefox*' '*chrome*' '*dotnet*' '*php*'
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install -y build-essential clang flex bison g++ gawk gettext libncurses-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget llvm
          sudo apt autoremove -y && sudo apt clean -y

      - name: Clone OpenWrt source
        run: |
          git clone --depth=1 -b ${{ env.OPENWRT_BRANCH }} ${{ env.OPENWRT_REPO }} openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy custom configuration and files
        run: |
          cd openwrt
          cp -v ../${{ env.CONFIG_FILE }} .config
          [ -d ../files ] && cp -r ../files ./ || true
          make defconfig

      - name: Build firmware
        run: |
          cd openwrt
          make
