name: Build OpenWrt for GL-MT6000 (Self-Hosted)

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "38 1 * * *"   # daily at 01:38 UTC

env:
  OPENWRT_REPO: https://github.com/openwrt/openwrt.git
  OPENWRT_BRANCH: openwrt-24.10
  CONFIG_FILE: wr3000.config
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_COMPRESS: "1"
  CCACHE_COMPILERCHECK: content

jobs:
  build:
    runs-on: self-hosted
    steps:

      # -------------------------------------------------
      # 0. CLEAN DIAGNOSTICS
      # -------------------------------------------------
      - name: Clean runner diagnostics
        run: |
          RUNNER_TEMP="${{ runner.temp }}"
          DIAG_PAGES="$RUNNER_TEMP/_diag/pages"
          echo "Cleaning: $DIAG_PAGES"
          [ -
