runs-on: self-hosted
name: Build OpenWrt for Cudy WR3000

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: 'OpenWrt version'
        default: 'openwrt-24.10'
      target:
        description: 'Target'
        default: 'mediatek/filogic'
      profile:
        description: 'Device profile'
        default: 'cudy_wr3000-v1'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
          g++-multilib gettext git libncurses5-dev libssl-dev rsync unzip zlib1g-dev \
          file wget subversion python3 python3-pip python3-lib2to3

      - name: Clone OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git -b ${{ github.event.inputs.openwrt_version }}
          if [ -f .config ]; then
            mv .config openwrt/.config
          else
            echo "Error: .config file not found in repository root"
            exit 1
          fi
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure and build
        run: |
          cd openwrt
          make defconfig
          make download -j$(nproc)
          make -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-cudy-wr3000
          path: openwrt/bin/targets/mediatek/filogic/
