name: Build OpenWrt 24.10.3 for Cudy WR3000

on:
  workflow_dispatch:
    inputs:
      openwrt_revision:
        description: 'OpenWrt Revision (e.g., r28872-daca7c049b)'
        required: true
        default: 'r28872-daca7c049b'
        type: string
      luci_commit:
        description: 'LuCI Commit (e.g., 923f8d9)'
        required: true
        default: '923f8d9'
        type: string
      custom_config:
        description: 'Custom Config Snippet (optional, e.g., "CONFIG_PACKAGE_wireguard-tools=y")'
        required: false
        default: ''
        type: string

env:
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  LUCI_URL: https://github.com/openwrt/luci.git
  BUILD_ROOT: ${{ github.workspace }}/openwrt
  TZ: UTC  # Adjust to your timezone, e.g., 'America/New_York'

jobs:
  build:
    name: Build Firmware
    runs-on: self-hosted  # Use your self-hosted runner label if customized

    steps:
      - name: Initialize Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3 python3-distutils rsync unzip wget zlib1g-dev file libelf-dev ecj javacc ninja-build ccache xsltproc libxml-parser-perl mercurial
          sudo apt-get clean
          sudo timedatectl set-timezone "${TZ}"

      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/local/lib/android
          df -h

      - name: Checkout OpenWrt Source
        run: |
          git clone --depth=1 ${REPO_URL} ${BUILD_ROOT}
          cd ${BUILD_ROOT}
          git checkout ${{ github.event.inputs.openwrt_revision || 'r28872-daca7c049b' }}
          git log -1 --oneline

      
        run: |
          cd ${BUILD_ROOT}
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      
        run: |
          cd ${BUILD_ROOT}
          sed -i 's|src-git luci https://github.com/openwrt/luci.git$|src-git luci ${LUCI_URL};${{ github.event.inputs.luci_commit || '923f8d9' }}|' feeds.conf.default
          ./scripts/feeds update luci
          ./scripts/feeds install -a -p luci

      
