name: Build OpenWrt for GL-MT6000 (Self-Hosted)

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "38 1 * * *"   # daily at 01:38 UTC

env:
  OPENWRT_REPO: https://github.com/openwrt/openwrt.git
  OPENWRT_BRANCH: openwrt-24.10
  CONFIG_FILE: wr3000.config
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_COMPRESS: "1"
  CCACHE_COMPILERCHECK: content

jobs:
  build:
    runs-on: self-hosted
    steps:

      # -------------------------------------------------
      # 0. CLEAN DIAGNOSTICS (Refactored for syntax safety)
      # -------------------------------------------------
      - name: Clean runner diagnostics
        run: |
          RUNNER_TEMP="${{ runner.temp }}"
          DIAG_PAGES="${RUNNER_TEMP}/_diag/pages"
          echo "Cleaning diagnostic pages: ${DIAG_PAGES}"
          if [ -d "${DIAG_PAGES}" ]; then
            rm -rf "${DIAG_PAGES}"/* || true
          fi

          DIAG_ROOT="${RUNNER_TEMP%/*}/_diag"
          echo "Cleaning diagnostic root: ${DIAG_ROOT}"
          if [ -d "${DIAG_ROOT}" ]; then
            find "${DIAG_ROOT}" -type f -name "*.log" -delete || true
          fi

      # -------------------------------------------------
      # 1. Checkout GL-MT6000 (Private Repo)
      # -------------------------------------------------
      - name: Checkout GL-MT6000 config
        uses: actions/checkout@v4
        with:
          repository: Christian720420/GL-MT6000
          path: source_repo
          token: ${{ github.token }}
          persist-credentials: true

      # -------------------------------------------------
      # 2. Install dependencies
      # -------------------------------------------------
      - name: Install dependencies
        run: |
          sudo -n apt update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt install -y
