name: Build OpenWrt for Cudy WR3000

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "38 1 * * *"

env:
  REMOTE_REPOSITORY: pesa1234/openwrt
  GH_TOKEN: ${{ github.token }}

jobs:
  check_commits:
    name: Check for new commits
    runs-on: ubuntu-24.04-arm
    outputs:
      remote_branch: ${{ steps.check_commits.outputs.remote_branch }}
      release_prefix: ${{ steps.check_commits.outputs.release_prefix }}
      new_commits: ${{ steps.check_commits.outputs.new_commits }}
      latest_commit_sha: ${{ steps.check_commits.outputs.latest_commit_sha }}
    steps:

  build:
    name: Build OpenWrt (Cudy WR3000)
    needs: check_commits
    if: github.event_name == 'workflow_dispatch' || needs.check_commits.outputs.new_commits == 'true'
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install dependencies
        run: |
          sudo apt remove -y '*cloud*' '*firefox*' '*chrome*' '*dotnet*' '*php*'
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install -y build-essential clang flex bison g++ gawk gettext libncurses-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget llvm
          sudo apt autoremove -y && sudo apt clean -y


      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: "builder_repo"

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install -a

      - name: Build firmware
        run: |
          make download -j$(nproc) || { echo "Retrying download..."; sleep 30; make download -j1 V=s; }
          make -j$(nproc) || { echo "Retrying build..."; sleep 30; make -j1 V=s; }
          mkdir -p firmware
          find ./bin -type f \( -iname 'openwrt-*-sysupgrade.bin' -or -iname 'sha256sums' -or -iname 'config.buildinfo' \) -exec mv -v {} ./firmware/ \; ||:
          mv .config firmware/full.config ||:

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cudy-wr3000-firmware
          path: firmware/*

      - name: Create release
        run: |
          RELEASE_DATE=$(date +%F)
          gh release delete "${{ needs.check_commits.outputs.release_prefix }}-${RELEASE_DATE}" --cleanup-tag -y --repo "${{ github.repository }}" ||:
          gh release create "${{ needs.check_commits.outputs.release_prefix }}-${RELEASE_DATE}" --repo "${{ github.repository }}" --latest --notes "### 🔄 Main Repository
          - **Repository:** [${{ env.REMOTE_REPOSITORY }}](https://github.com/${{ env.REMOTE_REPOSITORY }})
          - **Branch:** ${{ needs.check_commits.outputs.remote_branch }}
          - **Commit:** ${{ needs.check_commits.outputs.latest_commit_sha }}
          
          ### 🧩 Device Info
          - **Brand:** Cudy
          - **Model:** WR3000 (v1, v2)
          - **CPU:** MediaTek MT7981BA @1300 MHz (2 cores)
          - **Flash:** 16 MB
          - **RAM:** 256 MB
          - **Wi-Fi:** MT7981BA (2.4 GHz b/g/n/ax) + MT7976CN (5 GHz a/n/ac/ax)
          - **Ethernet:** 4× 1 Gbit LAN ports
          - **Release:** OpenWrt 24.10.2
          - **OEM Page:** [cudy.com](https://www.cudy.com)
          - **Forum:** [OpenWrt Cudy WR3000](https://forum.openwrt.org/search?q=WR3000)
          
          ### ⚙️ Build Configuration
          - **Config:** [${{ env.CONFIG_FILE }}](${{ env.CONFIG_FILE }})
          - **Features:** WiFi UCODE, Wireguard VPN, PBR, Adblock Fast
          - **Removed:** odhcp, upnp, iptables, avahi, samba, usb storage" \
          --title "OpenWrt Custom Release for Cudy WR3000 (${{ needs.check_commits.outputs.release_prefix }}-${RELEASE_DATE})" firmware/*

      - name: Clean up old releases
        run: |
          gh api repos/${{ github.repository }}/releases --paginate --jq '.[6:] | .[] | "\(.id) \(.tag_name)"' | while read id tag; do
            gh api -X DELETE "repos/${{ github.repository }}/releases/$id" && gh api -X DELETE "repos/${{ github.repository }}/git/refs/tags/$tag" 2>/dev/null ||:
          done
